# Generated by Django 3.1.4 on 2020-12-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201221_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='Name',
            new_name='name',
        ),
    ]
